scriptencoding utf-8

let s:save_cpo = &cpo
set cpo&vim

function! ccline#command#command()
  if !exists('s:session_id') || ccline#session_id() > s:session_id
    let s:user_command = s:get_user_command()
    let s:command = extend(deepcopy(s:default_command), s:user_command)
    let s:session_id = ccline#session_id()
  endif
  return s:command
endfunction

function! ccline#command#current_command(backward)
  let current_expr = ccline#command#current_expr(a:backward)
  if empty(current_expr)
    return ':'
  endif
  let command = ''
  for expr in current_expr
    let expr = ccline#command#expand_alias(expr)
    if !s:iscommand(expr)
      return ''
    endif
    let command = expr
    if get(ccline#command#command()[command], 'complete', '') !=# 'command'
      return command
    endif
  endfor
  return command
endfunction

function! ccline#command#current_expr(backward)
  let [part, space] = ccline#command#parse(a:backward)
  let exprs = s:split_list(part, '|')
  if empty(exprs)
    return []
  endif
  let current_expr = exprs[len(exprs) - 1]
  if empty(current_expr)
    return []
  endif
  if empty(space[len(space) - 1])
    call remove(current_expr, len(current_expr) - 1)
  endif
  if empty(current_expr)
    return []
  endif
  let current_expr[0] = s:separate_range(current_expr[0])[1]
  return current_expr
endfunction

function! s:iscommand(expr)
  return has_key(ccline#command#command(), a:expr)
endfunction

function! ccline#command#parse(str)
  let single_quote = "'"
  let double_quote = '"'
  let space = ' '
  let escape = '\'
  let bar = '|'

  let normal = 0
  let single_quote_inner = 1
  let double_quote_inner = 2
  let space_inner = 3

  let state = space_inner

  let endflag = 0
  let escapeflag = 0

  let result = []
  let spaceresult = []

  let part = ''
  let spacepart = ''

  for char in split(a:str, '\zs')
    if state == single_quote_inner
      if char ==# single_quote
        let endflag = !endflag
        let part .= char
        continue
      else
        if endflag
          let state = (char ==# space) ? space_inner : normal
          let endflag = 0
        else
          let part .= char
          continue
        endif
      endif
    elseif state == double_quote_inner
      if char ==# double_quote
        let endflag = !endflag
        let part .= char
        continue
      else
        if endflag
          let state = (char ==# space) ? space_inner : normal
          let endflag = 0
        else
          let part .= char
          continue
        endif
      endif
    endif

    if state == space_inner
      if char ==# space
        let spacepart .= char
      else
        let spaceresult += [spacepart]
        let spacepart = ''
        let state = normal
      endif
    endif

    if state == normal
      if char ==# single_quote
        let state = single_quote_inner
        let part .= char
      elseif char ==# double_quote
        let state = double_quote_inner
        let part .= char
      elseif char ==# space
        if escapeflag
          let part .= char
          let escapeflag = 0
        else
          let state = space_inner
          if !empty(part)
            let result += [part]
          endif
          let part = ''
          let spacepart .= char
        endif
      elseif char ==# escape
        let escapeflag = !escapeflag
        let part .= char
      elseif char ==# bar
        if escapeflag
          let part .= char
          let escapeflag = 0
        else
          if !empty(part)
            let result += [part]
          endif
          let result += [char]
          let part = ''
        endif
      else
        let escapeflag = 0
        let part .= char
      endif
    endif
  endfor
  if !empty(part)
    let result += [part]
  endif
  if !empty(spacepart)
    let spaceresult += [spacepart]
  endif
  if state != space_inner
    call add(spaceresult, '')
  endif
  return [result, spaceresult]
endfunction

function! s:split_list(list, separator)
  let result = []
  let e = 0
  for i in range(len(a:list))
    if a:list[i] ==# a:separator
      let result += [a:list[e : i - 1]]
      let e = i + 1
    endif
  endfor
  let result += [a:list[e : len(a:list) - 1]]
  return result
endfunction

function! s:combine(part, space)
  let result = []
  for i in range(len(a:part))
    let result += [a:space[i], a:part[i]]
  endfor
  " return result + [a:space[i + 1]]
  return result + [a:space[len(a:space) - 1]]
endfunction

" base code
" https://github.com/thinca/vim-ambicmd/blob/78fa88c5647071e73a3d21e5f575ed408f68aaaf/autoload/ambicmd.vim#L26
function! s:separate_range(line)
  let search_pattern = '\v/[^/]*\\@<!%(\\\\)*/|\?[^?]*\\@<!%(\\\\)*\?'
  let line_specifier = '\v%(\d+|[.$]|''\S|\\[/?&])?%([+-]\d*|' . search_pattern . ')*'
  let range_pattern = '\v^%(\%|' . line_specifier . '%([;,]' . line_specifier . ')*)'
  let range = matchstr(a:line, range_pattern)
  return [range, strpart(a:line, strlen(range))]
endfunction

function! s:get_user_command()
  let result = {}
  let command = split(ccline#complete#capture('command'), '[\r\n]')
  call remove(command, 0)
  for line in command
    let p = s:parse_command_list(line)
    let result[p[0]] = p[1]
  endfor
  return result
endfunction
function! s:parse_command_list(line)
  let first = strpart(a:line, 0, 2)
  let bang = (stridx(first, '!') >= 0)
  let register = (stridx(first, '"') >= 0)
  let buffer_local = (stridx(first, 'b') >= 0)
  let name = matchstr(strpart(a:line, 4), '^[A-Z]\S*')
  let name_len = strlen(name)
  if name_len <= 11
    let args = strpart(a:line, 16, 1)
    let range = matchstr(strpart(a:line, 21), '^\S\+')
    let complete = matchstr(strpart(a:line, 27), '^\S\+')
  else
    let args = strpart(a:line, name_len+5, 1)
    let range = matchstr(strpart(a:line, name_len+10), '^\S\+')
    let complete = matchstr(strpart(a:line, name_len+16), '^\S\+')
  endif
  return [name, {'bang': bang, 'register': register, 'buffer_local': buffer_local, 'args': args, 'range': range, 'complete': complete}]
endfunction

let s:default_command = {
\ '!': {'complete': 'shellcmd'},
\ '#': {},
\ '&': {},
\ '*': {},
\ '<': {},
\ '=': {},
\ '>': {},
\ '@': {},
\ 'Next': {},
\ 'Print': {},
\ 'X': {},
\ 'abbreviate': {},
\ 'abclear': {},
\ 'aboveleft': {},
\ 'all': {},
\ 'amenu': {},
\ 'anoremenu': {},
\ 'append': {},
\ 'argadd': {'complete': 'file'},
\ 'argdelete': {'complete': 'file'},
\ 'argdo': {'complete': 'command'},
\ 'argedit': {'complete': 'file'},
\ 'argglobal': {'complete': 'file'},
\ 'arglocal': {'complete': 'file'},
\ 'args': {'complete': 'file'},
\ 'argument': {'complete': ''},
\ 'ascii': {'complete': ''},
\ 'augroup': {'complete': 'augroup'},
\ 'aunmenu': {},
\ 'autocmd': {'complete': 'event'},
\ 'bNext': {},
\ 'badd': {},
\ 'ball': {},
\ 'bdelete': {},
\ 'behave': {'complete': 'behave'},
\ 'belowright': {},
\ 'bfirst': {},
\ 'blast': {},
\ 'bmodified': {},
\ 'bnext': {},
\ 'botright': {},
\ 'bprevious': {},
\ 'break': {'complete': ''},
\ 'breakadd': {},
\ 'breakdel': {},
\ 'breaklist': {},
\ 'brewind': {},
\ 'browse': {},
\ 'bufdo': {},
\ 'buffer': {'complete': 'buffer'},
\ 'buffers': {},
\ 'bunload': {},
\ 'bwipeout': {},
\ 'cNext': {},
\ 'cNfile': {},
\ 'cabbrev': {},
\ 'cabclear': {},
\ 'caddbuffer': {},
\ 'caddexpr': {},
\ 'caddfile': {},
\ 'call': {'complete': 'function'},
\ 'catch': {'complete': ''},
\ 'cbuffer': {},
\ 'cc': {'complete': ''},
\ 'cclose': {},
\ 'cd': {'complete': 'dir'},
\ 'center': {},
\ 'cexpr': {},
\ 'cfile': {},
\ 'cfirst': {},
\ 'cgetbuffer': {},
\ 'cgetexpr': {},
\ 'cgetfile': {},
\ 'change': {},
\ 'changes': {},
\ 'chdir': {'complete': 'dir'},
\ 'checkpath': {},
\ 'checktime': {},
\ 'clast': {},
\ 'clist': {},
\ 'close': {},
\ 'cmap': {'complete': 'mapping'},
\ 'cmapclear': {'complete': ''},
\ 'cmenu': {},
\ 'cnewer': {},
\ 'cnext': {},
\ 'cnfile': {},
\ 'cnoreabbrev': {},
\ 'cnoremap': {'complete': 'mapping'},
\ 'cnoremenu': {},
\ 'colder': {},
\ 'colorscheme': {'complete': 'color'},
\ 'comclear': {},
\ 'command': {'complete': 'command'},
\ 'compiler': {'complete': 'compiler'},
\ 'confirm': {},
\ 'continue': {},
\ 'copen': {},
\ 'copy': {},
\ 'cpfile': {},
\ 'cprevious': {},
\ 'cquit': {},
\ 'crewind': {},
\ 'cscope': {'complete': 'cscope'},
\ 'cstag': {},
\ 'cunabbrev': {},
\ 'cunmap': {'complete': 'mapping'},
\ 'cunmenu': {},
\ 'cwindow': {},
\ 'debug': {},
\ 'debuggreedy': {},
\ 'delcommand': {},
\ 'delete': {},
\ 'delfunction': {},
\ 'delmarks': {},
\ 'diffget': {},
\ 'diffoff': {},
\ 'diffpatch': {},
\ 'diffput': {},
\ 'diffsplit': {},
\ 'diffthis': {},
\ 'diffupdate': {},
\ 'digraphs': {},
\ 'display': {},
\ 'djump': {},
\ 'dlist': {},
\ 'doautoall': {},
\ 'doautocmd': {},
\ 'drop': {},
\ 'dsearch': {},
\ 'dsplit': {},
\ 'earlier': {},
\ 'echo': {'complete': 'function'},
\ 'echoerr': {'complete': 'function'},
\ 'echohl': {'complete': 'highlight'},
\ 'echomsg': {'complete': 'function'},
\ 'echon': {'complete': 'function'},
\ 'edit': {'complete': 'file'},
\ 'else': {'complete': ''},
\ 'elseif': {},
\ 'emenu': {},
\ 'endfor': {'complete': ''},
\ 'endfunction': {'complete': ''},
\ 'endif': {'complete': ''},
\ 'endtry': {'complete': ''},
\ 'endwhile': {'complete': ''},
\ 'enew': {'complete': ''},
\ 'ex': {},
\ 'execute': {},
\ 'exit': {},
\ 'exusage': {},
\ 'file': {},
\ 'files': {},
\ 'filetype': {},
\ 'finally': {},
\ 'find': {},
\ 'finish': {'complete': ''},
\ 'first': {'complete': ''},
\ 'fixdel': {},
\ 'fold': {'complete': ''},
\ 'foldclose': {'complete': ''},
\ 'folddoclosed': {'complete': 'command'},
\ 'folddoopen': {'complete': 'command'},
\ 'foldopen': {'complete': ''},
\ 'for': {},
\ 'function': {},
\ 'global': {},
\ 'goto': {},
\ 'grep': {},
\ 'grepadd': {},
\ 'gui': {},
\ 'gvim': {},
\ 'hardcopy': {},
\ 'help': {'complete': 'help'},
\ 'helpfind': {'complete': ''},
\ 'helpgrep': {'complete': ''},
\ 'helptags': {'complete': 'dir'},
\ 'hide': {},
\ 'highlight': {'complete': 'highlight'},
\ 'history': {'complete': 'history'},
\ 'iabbrev': {},
\ 'iabclear': {},
\ 'if': {},
\ 'ijump': {},
\ 'ilist': {},
\ 'imap': {'complete': 'mapping'},
\ 'imapclear': {'complete': ''},
\ 'imenu': {},
\ 'inoreabbrev': {},
\ 'inoremap': {'complete': 'mapping'},
\ 'inoremenu': {},
\ 'insert': {},
\ 'intro': {'complete': ''},
\ 'isearch': {},
\ 'isplit': {},
\ 'iunabbrev': {},
\ 'iunmap': {'complete': 'mapping'},
\ 'iunmenu': {},
\ 'join': {},
\ 'jumps': {'complete': ''},
\ 'k': {},
\ 'keepalt': {},
\ 'keepjumps': {},
\ 'keepmarks': {},
\ 'keeppatterns': {},
\ 'lNext': {},
\ 'lNfile': {},
\ 'laddbuffer': {},
\ 'laddexpr': {},
\ 'laddfile': {},
\ 'language': {},
\ 'last': {},
\ 'later': {},
\ 'lbuffer': {},
\ 'lcd': {'complete': 'dir'},
\ 'lchdir': {'complete': 'dir'},
\ 'lclose': {},
\ 'lcscope': {},
\ 'left': {},
\ 'leftabove': {},
\ 'let': {},
\ 'lexpr': {},
\ 'lfile': {},
\ 'lfirst': {},
\ 'lgetbuffer': {},
\ 'lgetexpr': {},
\ 'lgetfile': {},
\ 'lgrep': {},
\ 'lgrepadd': {},
\ 'lhelpgrep': {},
\ 'list': {},
\ 'll': {},
\ 'llast': {},
\ 'llist': {},
\ 'lmake': {'complete': 'file'},
\ 'lmap': {'complete': 'mapping'},
\ 'lmapclear': {'complete': ''},
\ 'lnewer': {},
\ 'lnext': {},
\ 'lnfile': {},
\ 'lnoremap': {'complete': 'mapping'},
\ 'loadkeymap': {},
\ 'loadview': {},
\ 'lockmarks': {},
\ 'lockvar': {},
\ 'lolder': {},
\ 'lopen': {},
\ 'lpfile': {},
\ 'lprevious': {},
\ 'lrewind': {},
\ 'ls': {},
\ 'ltag': {},
\ 'lua': {},
\ 'luado': {},
\ 'luafile': {},
\ 'lunmap': {'complete': 'mapping'},
\ 'lvimgrep': {},
\ 'lvimgrepadd': {},
\ 'lwindow': {},
\ 'make': {},
\ 'map': {'complete': 'mapping'},
\ 'mapclear': {'complete': ''},
\ 'mark': {},
\ 'marks': {},
\ 'match': {},
\ 'menu': {},
\ 'menutranslate': {},
\ 'messages': {},
\ 'mkexrc': {},
\ 'mksession': {},
\ 'mkspell': {},
\ 'mkview': {},
\ 'mkvimrc': {},
\ 'mode': {},
\ 'move': {},
\ 'mzfile': {},
\ 'mzscheme': {},
\ 'nbclose': {},
\ 'nbkey': {},
\ 'nbstart': {},
\ 'new': {'complete': 'file'},
\ 'next': {},
\ 'nmap': {'complete': 'mapping'},
\ 'nmapclear': {'complete': ''},
\ 'nmenu': {},
\ 'nnoremap': {'complete': 'mapping'},
\ 'nnoremenu': {},
\ 'noautocmd': {},
\ 'nohlsearch': {},
\ 'noreabbrev': {},
\ 'noremap': {'complete': 'mapping'},
\ 'noremenu': {},
\ 'normal': {},
\ 'noswapfile': {},
\ 'number': {},
\ 'nunmap': {'complete': 'mapping'},
\ 'nunmenu': {},
\ 'oldfiles': {},
\ 'omap': {'complete': 'mapping'},
\ 'omapclear': {'complete': ''},
\ 'omenu': {},
\ 'only': {},
\ 'onoremap': {'complete': 'mapping'},
\ 'onoremenu': {},
\ 'open': {},
\ 'options': {},
\ 'ounmap': {'complete': 'mapping'},
\ 'ounmenu': {},
\ 'ownsyntax': {'complete': 'syntax'},
\ 'pclose': {},
\ 'pedit': {'complete': 'file'},
\ 'perl': {},
\ 'perldo': {},
\ 'pop': {},
\ 'popup': {},
\ 'ppop': {},
\ 'preserve': {},
\ 'previous': {},
\ 'print': {},
\ 'profdel': {},
\ 'profile': {},
\ 'promptfind': {},
\ 'promptrepl': {},
\ 'psearch': {},
\ 'ptNext': {},
\ 'ptag': {},
\ 'ptfirst': {},
\ 'ptjump': {},
\ 'ptlast': {},
\ 'ptnext': {},
\ 'ptprevious': {},
\ 'ptrewind': {},
\ 'ptselect': {},
\ 'put': {},
\ 'pwd': {},
\ 'py3': {},
\ 'py3do': {},
\ 'py3file': {},
\ 'pydo': {},
\ 'pyfile': {},
\ 'python': {},
\ 'python3': {},
\ 'qall': {},
\ 'quit': {},
\ 'quitall': {},
\ 'read': {},
\ 'recover': {},
\ 'redir': {},
\ 'redo': {},
\ 'redraw': {},
\ 'redrawstatus': {},
\ 'registers': {},
\ 'resize': {},
\ 'retab': {},
\ 'return': {},
\ 'rewind': {},
\ 'right': {},
\ 'rightbelow': {},
\ 'ruby': {},
\ 'rubydo': {},
\ 'rubyfile': {},
\ 'rundo': {},
\ 'runtime': {},
\ 'rviminfo': {},
\ 'sNext': {},
\ 'sall': {},
\ 'sandbox': {},
\ 'sargument': {},
\ 'saveas': {},
\ 'sbNext': {},
\ 'sball': {},
\ 'sbfirst': {},
\ 'sblast': {},
\ 'sbmodified': {},
\ 'sbnext': {},
\ 'sbprevious': {},
\ 'sbrewind': {},
\ 'sbuffer': {},
\ 'scriptencoding': {},
\ 'scriptnames': {},
\ 'scscope': {},
\ 'set': {'complete': 'option'},
\ 'setfiletype': {'complete': 'filetype'},
\ 'setglobal': {},
\ 'setlocal': {'complete': 'option'},
\ 'sfind': {},
\ 'sfirst': {},
\ 'shell': {},
\ 'sign': {'complete': 'sign'},
\ 'silent': {},
\ 'simalt': {},
\ 'slast': {},
\ 'sleep': {'complete': ''},
\ 'smagic': {},
\ 'smap': {'complete': 'mapping'},
\ 'smapclear': {'complete': ''},
\ 'smenu': {},
\ 'snext': {},
\ 'sniff': {},
\ 'snomagic': {},
\ 'snoremap': {'complete': 'mapping'},
\ 'snoremenu': {},
\ 'sort': {},
\ 'source': {},
\ 'spelldump': {},
\ 'spellgood': {},
\ 'spellinfo': {},
\ 'spellrepall': {},
\ 'spellundo': {},
\ 'spellwrong': {},
\ 'split': {},
\ 'sprevious': {},
\ 'srewind': {},
\ 'stag': {},
\ 'startgreplace': {},
\ 'startinsert': {},
\ 'startreplace': {},
\ 'stjump': {},
\ 'stop': {},
\ 'stopinsert': {},
\ 'stselect': {},
\ 'substitute': {},
\ 'sunhide': {},
\ 'sunmap': {'complete': 'mapping'},
\ 'sunmenu': {},
\ 'suspend': {},
\ 'sview': {},
\ 'swapname': {},
\ 'syncbind': {},
\ 'syntax': {},
\ 'syntime': {'complete': 'syntime'},
\ 't': {},
\ 'tNext': {},
\ 'tab': {'complete': 'command'},
\ 'tabNext': {},
\ 'tabclose': {},
\ 'tabdo': {},
\ 'tabedit': {'complete': 'file'},
\ 'tabfind': {},
\ 'tabfirst': {},
\ 'tablast': {},
\ 'tabmove': {},
\ 'tabnew': {'complete': 'file'},
\ 'tabnext': {},
\ 'tabonly': {},
\ 'tabprevious': {},
\ 'tabrewind': {},
\ 'tabs': {},
\ 'tag': {},
\ 'tags': {},
\ 'tcl': {},
\ 'tcldo': {},
\ 'tclfile': {},
\ 'tearoff': {},
\ 'tfirst': {},
\ 'throw': {},
\ 'tjump': {},
\ 'tlast': {},
\ 'tmenu': {},
\ 'tnext': {},
\ 'topleft': {},
\ 'tprevious': {},
\ 'trewind': {},
\ 'try': {},
\ 'tselect': {},
\ 'tunmenu': {},
\ 'unabbreviate': {},
\ 'undo': {},
\ 'undojoin': {},
\ 'undolist': {},
\ 'unhide': {},
\ 'unlet': {},
\ 'unlockvar': {},
\ 'unmap': {'complete': 'mapping'},
\ 'unmenu': {},
\ 'unsilent': {},
\ 'update': {},
\ 'verbose': {},
\ 'version': {},
\ 'vertical': {},
\ 'vglobal': {},
\ 'view': {},
\ 'vimgrep': {},
\ 'vimgrepadd': {},
\ 'visual': {},
\ 'viusage': {},
\ 'vmap': {'complete': 'mapping'},
\ 'vmapclear': {'complete': ''},
\ 'vmenu': {},
\ 'vnew': {'complete': 'file'},
\ 'vnoremap': {'complete': 'mapping'},
\ 'vnoremenu': {},
\ 'vsplit': {},
\ 'vunmap': {'complete': 'mapping'},
\ 'vunmenu': {},
\ 'wNext': {},
\ 'wall': {},
\ 'while': {},
\ 'wincmd': {},
\ 'windo': {},
\ 'winpos': {},
\ 'winsize': {},
\ 'wnext': {},
\ 'wprevious': {},
\ 'wq': {},
\ 'wqall': {},
\ 'write': {},
\ 'wsverb': {},
\ 'wundo': {},
\ 'wviminfo': {},
\ 'xall': {},
\ 'xit': {},
\ 'xmap': {'complete': 'mapping'},
\ 'xmapclear': {'complete': ''},
\ 'xmenu': {},
\ 'xnoremap': {'complete': 'mapping'},
\ 'xnoremenu': {},
\ 'xunmap': {'complete': 'mapping'},
\ 'xunmenu': {},
\ 'yank': {},
\ 'z': {},
\ '~': {},
\ }

function! ccline#command#expand_alias(expr)
  return get(s:alias_dic, a:expr, a:expr)
endfunction

let s:alias_dic = {
\ 'a': 'append',
\ 'ab': 'abbreviate',
\ 'abb': 'abbreviate',
\ 'abbr': 'abbreviate',
\ 'abbre': 'abbreviate',
\ 'abbrev': 'abbreviate',
\ 'abbrevi': 'abbreviate',
\ 'abbrevia': 'abbreviate',
\ 'abbreviat': 'abbreviate',
\ 'abc': 'abclear',
\ 'abcl': 'abclear',
\ 'abcle': 'abclear',
\ 'abclea': 'abclear',
\ 'abo': 'aboveleft',
\ 'abov': 'aboveleft',
\ 'above': 'aboveleft',
\ 'abovel': 'aboveleft',
\ 'abovele': 'aboveleft',
\ 'abovelef': 'aboveleft',
\ 'al': 'all',
\ 'am': 'amenu',
\ 'ame': 'amenu',
\ 'amen': 'amenu',
\ 'an': 'anoremenu',
\ 'ano': 'anoremenu',
\ 'anor': 'anoremenu',
\ 'anore': 'anoremenu',
\ 'anorem': 'anoremenu',
\ 'anoreme': 'anoremenu',
\ 'anoremen': 'anoremenu',
\ 'ap': 'append',
\ 'app': 'append',
\ 'appe': 'append',
\ 'appen': 'append',
\ 'ar': 'args',
\ 'arg': 'args',
\ 'arga': 'argadd',
\ 'argad': 'argadd',
\ 'argd': 'argdelete',
\ 'argde': 'argdelete',
\ 'argdel': 'argdelete',
\ 'argdele': 'argdelete',
\ 'argdelet': 'argdelete',
\ 'arge': 'argedit',
\ 'arged': 'argedit',
\ 'argedi': 'argedit',
\ 'argg': 'argglobal',
\ 'arggl': 'argglobal',
\ 'argglo': 'argglobal',
\ 'argglob': 'argglobal',
\ 'arggloba': 'argglobal',
\ 'argl': 'arglocal',
\ 'arglo': 'arglocal',
\ 'argloc': 'arglocal',
\ 'argloca': 'arglocal',
\ 'argu': 'argument',
\ 'argum': 'argument',
\ 'argume': 'argument',
\ 'argumen': 'argument',
\ 'as': 'ascii',
\ 'asc': 'ascii',
\ 'asci': 'ascii',
\ 'au': 'autocmd',
\ 'aug': 'augroup',
\ 'augr': 'augroup',
\ 'augro': 'augroup',
\ 'augrou': 'augroup',
\ 'aun': 'aunmenu',
\ 'aunm': 'aunmenu',
\ 'aunme': 'aunmenu',
\ 'aunmen': 'aunmenu',
\ 'aut': 'autocmd',
\ 'auto': 'autocmd',
\ 'autoc': 'autocmd',
\ 'autocm': 'autocmd',
\ 'b': 'buffer',
\ 'bN': 'bNext',
\ 'bNe': 'bNext',
\ 'bNex': 'bNext',
\ 'ba': 'ball',
\ 'bad': 'badd',
\ 'bal': 'ball',
\ 'bd': 'bdelete',
\ 'bde': 'bdelete',
\ 'bdel': 'bdelete',
\ 'bdele': 'bdelete',
\ 'bdelet': 'bdelete',
\ 'be': 'behave',
\ 'beh': 'behave',
\ 'beha': 'behave',
\ 'behav': 'behave',
\ 'bel': 'belowright',
\ 'belo': 'belowright',
\ 'below': 'belowright',
\ 'belowr': 'belowright',
\ 'belowri': 'belowright',
\ 'belowrig': 'belowright',
\ 'belowrigh': 'belowright',
\ 'bf': 'bfirst',
\ 'bfi': 'bfirst',
\ 'bfir': 'bfirst',
\ 'bfirs': 'bfirst',
\ 'bl': 'blast',
\ 'bla': 'blast',
\ 'blas': 'blast',
\ 'bm': 'bmodified',
\ 'bmo': 'bmodified',
\ 'bmod': 'bmodified',
\ 'bmodi': 'bmodified',
\ 'bmodif': 'bmodified',
\ 'bmodifi': 'bmodified',
\ 'bmodifie': 'bmodified',
\ 'bn': 'bnext',
\ 'bne': 'bnext',
\ 'bnex': 'bnext',
\ 'bo': 'botright',
\ 'bot': 'botright',
\ 'botr': 'botright',
\ 'botri': 'botright',
\ 'botrig': 'botright',
\ 'botrigh': 'botright',
\ 'bp': 'bprevious',
\ 'bpr': 'bprevious',
\ 'bpre': 'bprevious',
\ 'bprev': 'bprevious',
\ 'bprevi': 'bprevious',
\ 'bprevio': 'bprevious',
\ 'bpreviou': 'bprevious',
\ 'br': 'brewind',
\ 'bre': 'brewind',
\ 'brea': 'break',
\ 'breaka': 'breakadd',
\ 'breakad': 'breakadd',
\ 'breakd': 'breakdel',
\ 'breakde': 'breakdel',
\ 'breakl': 'breaklist',
\ 'breakli': 'breaklist',
\ 'breaklis': 'breaklist',
\ 'brew': 'brewind',
\ 'brewi': 'brewind',
\ 'brewin': 'brewind',
\ 'bro': 'browse',
\ 'brow': 'browse',
\ 'brows': 'browse',
\ 'bu': 'buffer',
\ 'buf': 'buffer',
\ 'buff': 'buffer',
\ 'buffe': 'buffer',
\ 'bun': 'bunload',
\ 'bunl': 'bunload',
\ 'bunlo': 'bunload',
\ 'bunloa': 'bunload',
\ 'bw': 'bwipeout',
\ 'bwi': 'bwipeout',
\ 'bwip': 'bwipeout',
\ 'bwipe': 'bwipeout',
\ 'bwipeo': 'bwipeout',
\ 'bwipeou': 'bwipeout',
\ 'c': 'change',
\ 'cN': 'cNext',
\ 'cNe': 'cNext',
\ 'cNex': 'cNext',
\ 'cNf': 'cNfile',
\ 'cNfi': 'cNfile',
\ 'cNfil': 'cNfile',
\ 'ca': 'cabbrev',
\ 'cab': 'cabbrev',
\ 'cabb': 'cabbrev',
\ 'cabbr': 'cabbrev',
\ 'cabbre': 'cabbrev',
\ 'cabc': 'cabclear',
\ 'cabcl': 'cabclear',
\ 'cabcle': 'cabclear',
\ 'cabclea': 'cabclear',
\ 'cad': 'caddbuffer',
\ 'cadd': 'caddbuffer',
\ 'caddb': 'caddbuffer',
\ 'caddbu': 'caddbuffer',
\ 'caddbuf': 'caddbuffer',
\ 'caddbuff': 'caddbuffer',
\ 'caddbuffe': 'caddbuffer',
\ 'cadde': 'caddexpr',
\ 'caddex': 'caddexpr',
\ 'caddexp': 'caddexpr',
\ 'caddf': 'caddfile',
\ 'caddfi': 'caddfile',
\ 'caddfil': 'caddfile',
\ 'cal': 'call',
\ 'cat': 'catch',
\ 'catc': 'catch',
\ 'cb': 'cbuffer',
\ 'cbu': 'cbuffer',
\ 'cbuf': 'cbuffer',
\ 'cbuff': 'cbuffer',
\ 'cbuffe': 'cbuffer',
\ 'ccl': 'cclose',
\ 'cclo': 'cclose',
\ 'cclos': 'cclose',
\ 'ce': 'center',
\ 'cen': 'center',
\ 'cent': 'center',
\ 'cente': 'center',
\ 'cex': 'cexpr',
\ 'cexp': 'cexpr',
\ 'cf': 'cfile',
\ 'cfi': 'cfile',
\ 'cfil': 'cfile',
\ 'cfir': 'cfirst',
\ 'cfirs': 'cfirst',
\ 'cg': 'cgetfile',
\ 'cge': 'cgetfile',
\ 'cget': 'cgetfile',
\ 'cgetb': 'cgetbuffer',
\ 'cgetbu': 'cgetbuffer',
\ 'cgetbuf': 'cgetbuffer',
\ 'cgetbuff': 'cgetbuffer',
\ 'cgetbuffe': 'cgetbuffer',
\ 'cgete': 'cgetexpr',
\ 'cgetex': 'cgetexpr',
\ 'cgetexp': 'cgetexpr',
\ 'cgetf': 'cgetfile',
\ 'cgetfi': 'cgetfile',
\ 'cgetfil': 'cgetfile',
\ 'ch': 'change',
\ 'cha': 'change',
\ 'chan': 'change',
\ 'chang': 'change',
\ 'chd': 'chdir',
\ 'chdi': 'chdir',
\ 'che': 'checkpath',
\ 'chec': 'checkpath',
\ 'check': 'checkpath',
\ 'checkp': 'checkpath',
\ 'checkpa': 'checkpath',
\ 'checkpat': 'checkpath',
\ 'checkt': 'checktime',
\ 'checkti': 'checktime',
\ 'checktim': 'checktime',
\ 'cl': 'clist',
\ 'cla': 'clast',
\ 'clas': 'clast',
\ 'cli': 'clist',
\ 'clis': 'clist',
\ 'clo': 'close',
\ 'clos': 'close',
\ 'cm': 'cmap',
\ 'cma': 'cmap',
\ 'cmapc': 'cmapclear',
\ 'cmapcl': 'cmapclear',
\ 'cmapcle': 'cmapclear',
\ 'cmapclea': 'cmapclear',
\ 'cme': 'cmenu',
\ 'cmen': 'cmenu',
\ 'cn': 'cnext',
\ 'cne': 'cnext',
\ 'cnew': 'cnewer',
\ 'cnewe': 'cnewer',
\ 'cnex': 'cnext',
\ 'cnf': 'cnfile',
\ 'cnfi': 'cnfile',
\ 'cnfil': 'cnfile',
\ 'cno': 'cnoremap',
\ 'cnor': 'cnoremap',
\ 'cnore': 'cnoremap',
\ 'cnorea': 'cnoreabbrev',
\ 'cnoreab': 'cnoreabbrev',
\ 'cnoreabb': 'cnoreabbrev',
\ 'cnoreabbr': 'cnoreabbrev',
\ 'cnoreabbre': 'cnoreabbrev',
\ 'cnorem': 'cnoremap',
\ 'cnorema': 'cnoremap',
\ 'cnoreme': 'cnoremenu',
\ 'cnoremen': 'cnoremenu',
\ 'co': 'copy',
\ 'col': 'colder',
\ 'cold': 'colder',
\ 'colde': 'colder',
\ 'colo': 'colorscheme',
\ 'color': 'colorscheme',
\ 'colors': 'colorscheme',
\ 'colorsc': 'colorscheme',
\ 'colorsch': 'colorscheme',
\ 'colorsche': 'colorscheme',
\ 'colorschem': 'colorscheme',
\ 'com': 'command',
\ 'comc': 'comclear',
\ 'comcl': 'comclear',
\ 'comcle': 'comclear',
\ 'comclea': 'comclear',
\ 'comm': 'command',
\ 'comma': 'command',
\ 'comman': 'command',
\ 'comp': 'compiler',
\ 'compi': 'compiler',
\ 'compil': 'compiler',
\ 'compile': 'compiler',
\ 'con': 'continue',
\ 'conf': 'confirm',
\ 'confi': 'confirm',
\ 'confir': 'confirm',
\ 'cont': 'continue',
\ 'conti': 'continue',
\ 'contin': 'continue',
\ 'continu': 'continue',
\ 'cop': 'copy',
\ 'cope': 'copen',
\ 'cp': 'cprevious',
\ 'cpf': 'cpfile',
\ 'cpfi': 'cpfile',
\ 'cpfil': 'cpfile',
\ 'cpr': 'cprevious',
\ 'cpre': 'cprevious',
\ 'cprev': 'cprevious',
\ 'cprevi': 'cprevious',
\ 'cprevio': 'cprevious',
\ 'cpreviou': 'cprevious',
\ 'cq': 'cquit',
\ 'cqu': 'cquit',
\ 'cqui': 'cquit',
\ 'cr': 'crewind',
\ 'cre': 'crewind',
\ 'crew': 'crewind',
\ 'crewi': 'crewind',
\ 'crewin': 'crewind',
\ 'cs': 'cscope',
\ 'csc': 'cscope',
\ 'csco': 'cscope',
\ 'cscop': 'cscope',
\ 'cst': 'cstag',
\ 'csta': 'cstag',
\ 'cu': 'cunmap',
\ 'cun': 'cunmap',
\ 'cuna': 'cunabbrev',
\ 'cunab': 'cunabbrev',
\ 'cunabb': 'cunabbrev',
\ 'cunabbr': 'cunabbrev',
\ 'cunabbre': 'cunabbrev',
\ 'cunm': 'cunmap',
\ 'cunma': 'cunmap',
\ 'cunme': 'cunmenu',
\ 'cunmen': 'cunmenu',
\ 'cw': 'cwindow',
\ 'cwi': 'cwindow',
\ 'cwin': 'cwindow',
\ 'cwind': 'cwindow',
\ 'cwindo': 'cwindow',
\ 'd': 'delete',
\ 'de': 'delete',
\ 'deb': 'debug',
\ 'debu': 'debug',
\ 'debugg': 'debuggreedy',
\ 'debuggr': 'debuggreedy',
\ 'debuggre': 'debuggreedy',
\ 'debuggree': 'debuggreedy',
\ 'debuggreed': 'debuggreedy',
\ 'del': 'delete',
\ 'delc': 'delcommand',
\ 'delco': 'delcommand',
\ 'delcom': 'delcommand',
\ 'delcomm': 'delcommand',
\ 'delcomma': 'delcommand',
\ 'delcomman': 'delcommand',
\ 'dele': 'delete',
\ 'delet': 'delete',
\ 'delf': 'delfunction',
\ 'delfu': 'delfunction',
\ 'delfun': 'delfunction',
\ 'delfunc': 'delfunction',
\ 'delfunct': 'delfunction',
\ 'delfuncti': 'delfunction',
\ 'delfunctio': 'delfunction',
\ 'delm': 'delmarks',
\ 'delma': 'delmarks',
\ 'delmar': 'delmarks',
\ 'delmark': 'delmarks',
\ 'di': 'display',
\ 'dif': 'diffupdate',
\ 'diff': 'diffupdate',
\ 'diffg': 'diffget',
\ 'diffge': 'diffget',
\ 'diffo': 'diffoff',
\ 'diffof': 'diffoff',
\ 'diffp': 'diffpatch',
\ 'diffpa': 'diffpatch',
\ 'diffpat': 'diffpatch',
\ 'diffpatc': 'diffpatch',
\ 'diffpu': 'diffput',
\ 'diffs': 'diffsplit',
\ 'diffsp': 'diffsplit',
\ 'diffspl': 'diffsplit',
\ 'diffspli': 'diffsplit',
\ 'diffu': 'diffupdate',
\ 'diffup': 'diffupdate',
\ 'diffupd': 'diffupdate',
\ 'diffupda': 'diffupdate',
\ 'diffupdat': 'diffupdate',
\ 'dig': 'digraphs',
\ 'digr': 'digraphs',
\ 'digra': 'digraphs',
\ 'digrap': 'digraphs',
\ 'digraph': 'digraphs',
\ 'dis': 'display',
\ 'disp': 'display',
\ 'displ': 'display',
\ 'displa': 'display',
\ 'dj': 'djump',
\ 'dju': 'djump',
\ 'djum': 'djump',
\ 'dli': 'dlist',
\ 'dlis': 'dlist',
\ 'do': 'doautocmd',
\ 'doa': 'doautocmd',
\ 'doau': 'doautocmd',
\ 'doaut': 'doautocmd',
\ 'doauto': 'doautocmd',
\ 'doautoa': 'doautoall',
\ 'doautoal': 'doautoall',
\ 'doautoc': 'doautocmd',
\ 'doautocm': 'doautocmd',
\ 'dr': 'drop',
\ 'dro': 'drop',
\ 'ds': 'dsearch',
\ 'dse': 'dsearch',
\ 'dsea': 'dsearch',
\ 'dsear': 'dsearch',
\ 'dsearc': 'dsearch',
\ 'dsp': 'dsplit',
\ 'dspl': 'dsplit',
\ 'dspli': 'dsplit',
\ 'e': 'edit',
\ 'ea': 'earlier',
\ 'ear': 'earlier',
\ 'earl': 'earlier',
\ 'earli': 'earlier',
\ 'earlie': 'earlier',
\ 'ec': 'echo',
\ 'ech': 'echo',
\ 'echoe': 'echoerr',
\ 'echoer': 'echoerr',
\ 'echoh': 'echohl',
\ 'echom': 'echomsg',
\ 'echoms': 'echomsg',
\ 'ed': 'edit',
\ 'edi': 'edit',
\ 'el': 'else',
\ 'els': 'else',
\ 'elsei': 'elseif',
\ 'em': 'emenu',
\ 'eme': 'emenu',
\ 'emen': 'emenu',
\ 'en': 'endif',
\ 'end': 'endif',
\ 'endf': 'endfunction',
\ 'endfo': 'endfor',
\ 'endfu': 'endfunction',
\ 'endfun': 'endfunction',
\ 'endfunc': 'endfunction',
\ 'endfunct': 'endfunction',
\ 'endfuncti': 'endfunction',
\ 'endfunctio': 'endfunction',
\ 'endi': 'endif',
\ 'endt': 'endtry',
\ 'endtr': 'endtry',
\ 'endw': 'endwhile',
\ 'endwh': 'endwhile',
\ 'endwhi': 'endwhile',
\ 'endwhil': 'endwhile',
\ 'ene': 'enew',
\ 'exe': 'execute',
\ 'exec': 'execute',
\ 'execu': 'execute',
\ 'execut': 'execute',
\ 'exi': 'exit',
\ 'exu': 'exusage',
\ 'exus': 'exusage',
\ 'exusa': 'exusage',
\ 'exusag': 'exusage',
\ 'f': 'file',
\ 'fi': 'file',
\ 'fil': 'file',
\ 'filet': 'filetype',
\ 'filety': 'filetype',
\ 'filetyp': 'filetype',
\ 'fin': 'find',
\ 'fina': 'finally',
\ 'final': 'finally',
\ 'finall': 'finally',
\ 'fini': 'finish',
\ 'finis': 'finish',
\ 'fir': 'first',
\ 'firs': 'first',
\ 'fix': 'fixdel',
\ 'fixd': 'fixdel',
\ 'fixde': 'fixdel',
\ 'fo': 'fold',
\ 'fol': 'fold',
\ 'foldc': 'foldclose',
\ 'foldcl': 'foldclose',
\ 'foldclo': 'foldclose',
\ 'foldclos': 'foldclose',
\ 'foldd': 'folddoopen',
\ 'folddo': 'folddoopen',
\ 'folddoc': 'folddoclosed',
\ 'folddocl': 'folddoclosed',
\ 'folddoclo': 'folddoclosed',
\ 'folddoclos': 'folddoclosed',
\ 'folddoclose': 'folddoclosed',
\ 'folddoo': 'folddoopen',
\ 'folddoop': 'folddoopen',
\ 'folddoope': 'folddoopen',
\ 'foldo': 'foldopen',
\ 'foldop': 'foldopen',
\ 'foldope': 'foldopen',
\ 'fu': 'function',
\ 'fun': 'function',
\ 'func': 'function',
\ 'funct': 'function',
\ 'functi': 'function',
\ 'functio': 'function',
\ 'g': 'global',
\ 'gl': 'global',
\ 'glo': 'global',
\ 'glob': 'global',
\ 'globa': 'global',
\ 'go': 'goto',
\ 'got': 'goto',
\ 'gr': 'grep',
\ 'gre': 'grep',
\ 'grepa': 'grepadd',
\ 'grepad': 'grepadd',
\ 'gu': 'gui',
\ 'gv': 'gvim',
\ 'gvi': 'gvim',
\ 'h': 'help',
\ 'ha': 'hardcopy',
\ 'har': 'hardcopy',
\ 'hard': 'hardcopy',
\ 'hardc': 'hardcopy',
\ 'hardco': 'hardcopy',
\ 'hardcop': 'hardcopy',
\ 'he': 'help',
\ 'hel': 'help',
\ 'helpf': 'helpfind',
\ 'helpfi': 'helpfind',
\ 'helpfin': 'helpfind',
\ 'helpg': 'helpgrep',
\ 'helpgr': 'helpgrep',
\ 'helpgre': 'helpgrep',
\ 'helpt': 'helptags',
\ 'helpta': 'helptags',
\ 'helptag': 'helptags',
\ 'hi': 'highlight',
\ 'hid': 'hide',
\ 'hig': 'highlight',
\ 'high': 'highlight',
\ 'highl': 'highlight',
\ 'highli': 'highlight',
\ 'highlig': 'highlight',
\ 'highligh': 'highlight',
\ 'his': 'history',
\ 'hist': 'history',
\ 'histo': 'history',
\ 'histor': 'history',
\ 'i': 'insert',
\ 'ia': 'iabbrev',
\ 'iab': 'iabbrev',
\ 'iabb': 'iabbrev',
\ 'iabbr': 'iabbrev',
\ 'iabbre': 'iabbrev',
\ 'iabc': 'iabclear',
\ 'iabcl': 'iabclear',
\ 'iabcle': 'iabclear',
\ 'iabclea': 'iabclear',
\ 'ij': 'ijump',
\ 'iju': 'ijump',
\ 'ijum': 'ijump',
\ 'il': 'ilist',
\ 'ili': 'ilist',
\ 'ilis': 'ilist',
\ 'im': 'imap',
\ 'ima': 'imap',
\ 'imapc': 'imapclear',
\ 'imapcl': 'imapclear',
\ 'imapcle': 'imapclear',
\ 'imapclea': 'imapclear',
\ 'ime': 'imenu',
\ 'imen': 'imenu',
\ 'in': 'insert',
\ 'ino': 'inoremap',
\ 'inor': 'inoremap',
\ 'inore': 'inoremap',
\ 'inorea': 'inoreabbrev',
\ 'inoreab': 'inoreabbrev',
\ 'inoreabb': 'inoreabbrev',
\ 'inoreabbr': 'inoreabbrev',
\ 'inoreabbre': 'inoreabbrev',
\ 'inorem': 'inoremap',
\ 'inorema': 'inoremap',
\ 'inoreme': 'inoremenu',
\ 'inoremen': 'inoremenu',
\ 'ins': 'insert',
\ 'inse': 'insert',
\ 'inser': 'insert',
\ 'int': 'intro',
\ 'intr': 'intro',
\ 'is': 'isearch',
\ 'ise': 'isearch',
\ 'isea': 'isearch',
\ 'isear': 'isearch',
\ 'isearc': 'isearch',
\ 'isp': 'isplit',
\ 'ispl': 'isplit',
\ 'ispli': 'isplit',
\ 'iu': 'iunmap',
\ 'iun': 'iunmap',
\ 'iuna': 'iunabbrev',
\ 'iunab': 'iunabbrev',
\ 'iunabb': 'iunabbrev',
\ 'iunabbr': 'iunabbrev',
\ 'iunabbre': 'iunabbrev',
\ 'iunm': 'iunmap',
\ 'iunma': 'iunmap',
\ 'iunme': 'iunmenu',
\ 'iunmen': 'iunmenu',
\ 'j': 'join',
\ 'jo': 'join',
\ 'joi': 'join',
\ 'ju': 'jumps',
\ 'jum': 'jumps',
\ 'jump': 'jumps',
\ 'kee': 'keepmarks',
\ 'keep': 'keepmarks',
\ 'keepa': 'keepalt',
\ 'keepal': 'keepalt',
\ 'keepj': 'keepjumps',
\ 'keepju': 'keepjumps',
\ 'keepjum': 'keepjumps',
\ 'keepjump': 'keepjumps',
\ 'keepm': 'keepmarks',
\ 'keepma': 'keepmarks',
\ 'keepmar': 'keepmarks',
\ 'keepmark': 'keepmarks',
\ 'l': 'list',
\ 'lN': 'lNext',
\ 'lNe': 'lNext',
\ 'lNex': 'lNext',
\ 'lNf': 'lNfile',
\ 'lNfi': 'lNfile',
\ 'lNfil': 'lNfile',
\ 'la': 'last',
\ 'lad': 'laddexpr',
\ 'ladd': 'laddexpr',
\ 'laddb': 'laddbuffer',
\ 'laddbu': 'laddbuffer',
\ 'laddbuf': 'laddbuffer',
\ 'laddbuff': 'laddbuffer',
\ 'laddbuffe': 'laddbuffer',
\ 'ladde': 'laddexpr',
\ 'laddex': 'laddexpr',
\ 'laddexp': 'laddexpr',
\ 'laddf': 'laddfile',
\ 'laddfi': 'laddfile',
\ 'laddfil': 'laddfile',
\ 'lan': 'language',
\ 'lang': 'language',
\ 'langu': 'language',
\ 'langua': 'language',
\ 'languag': 'language',
\ 'las': 'last',
\ 'lat': 'later',
\ 'late': 'later',
\ 'lb': 'lbuffer',
\ 'lbu': 'lbuffer',
\ 'lbuf': 'lbuffer',
\ 'lbuff': 'lbuffer',
\ 'lbuffe': 'lbuffer',
\ 'lc': 'lcd',
\ 'lch': 'lchdir',
\ 'lchd': 'lchdir',
\ 'lchdi': 'lchdir',
\ 'lcl': 'lclose',
\ 'lclo': 'lclose',
\ 'lclos': 'lclose',
\ 'le': 'left',
\ 'lef': 'left',
\ 'lefta': 'leftabove',
\ 'leftab': 'leftabove',
\ 'leftabo': 'leftabove',
\ 'leftabov': 'leftabove',
\ 'lex': 'lexpr',
\ 'lexp': 'lexpr',
\ 'lf': 'lfile',
\ 'lfi': 'lfile',
\ 'lfil': 'lfile',
\ 'lfir': 'lfirst',
\ 'lfirs': 'lfirst',
\ 'lg': 'lgetfile',
\ 'lge': 'lgetfile',
\ 'lget': 'lgetfile',
\ 'lgetb': 'lgetbuffer',
\ 'lgetbu': 'lgetbuffer',
\ 'lgetbuf': 'lgetbuffer',
\ 'lgetbuff': 'lgetbuffer',
\ 'lgetbuffe': 'lgetbuffer',
\ 'lgete': 'lgetexpr',
\ 'lgetex': 'lgetexpr',
\ 'lgetexp': 'lgetexpr',
\ 'lgetf': 'lgetfile',
\ 'lgetfi': 'lgetfile',
\ 'lgetfil': 'lgetfile',
\ 'lgr': 'lgrep',
\ 'lgre': 'lgrep',
\ 'lgrepa': 'lgrepadd',
\ 'lgrepad': 'lgrepadd',
\ 'lh': 'lhelpgrep',
\ 'lhe': 'lhelpgrep',
\ 'lhel': 'lhelpgrep',
\ 'lhelp': 'lhelpgrep',
\ 'lhelpg': 'lhelpgrep',
\ 'lhelpgr': 'lhelpgrep',
\ 'lhelpgre': 'lhelpgrep',
\ 'li': 'list',
\ 'lis': 'list',
\ 'lla': 'llast',
\ 'llas': 'llast',
\ 'lli': 'llist',
\ 'llis': 'llist',
\ 'lm': 'lmap',
\ 'lma': 'lmap',
\ 'lmak': 'lmake',
\ 'lmapc': 'lmapclear',
\ 'lmapcl': 'lmapclear',
\ 'lmapcle': 'lmapclear',
\ 'lmapclea': 'lmapclear',
\ 'ln': 'lnoremap',
\ 'lne': 'lnext',
\ 'lnew': 'lnewer',
\ 'lnewe': 'lnewer',
\ 'lnex': 'lnext',
\ 'lnf': 'lnfile',
\ 'lnfi': 'lnfile',
\ 'lnfil': 'lnfile',
\ 'lno': 'lnoremap',
\ 'lnor': 'lnoremap',
\ 'lnore': 'lnoremap',
\ 'lnorem': 'lnoremap',
\ 'lnorema': 'lnoremap',
\ 'lo': 'loadview',
\ 'loa': 'loadview',
\ 'load': 'loadview',
\ 'loadk': 'loadkeymap',
\ 'loadke': 'loadkeymap',
\ 'loadkey': 'loadkeymap',
\ 'loadkeym': 'loadkeymap',
\ 'loadkeyma': 'loadkeymap',
\ 'loadv': 'loadview',
\ 'loadvi': 'loadview',
\ 'loadvie': 'loadview',
\ 'loc': 'lockmarks',
\ 'lock': 'lockmarks',
\ 'lockm': 'lockmarks',
\ 'lockma': 'lockmarks',
\ 'lockmar': 'lockmarks',
\ 'lockmark': 'lockmarks',
\ 'lockv': 'lockvar',
\ 'lockva': 'lockvar',
\ 'lol': 'lolder',
\ 'lold': 'lolder',
\ 'lolde': 'lolder',
\ 'lope': 'lopen',
\ 'lp': 'lprevious',
\ 'lpf': 'lpfile',
\ 'lpfi': 'lpfile',
\ 'lpfil': 'lpfile',
\ 'lpr': 'lprevious',
\ 'lpre': 'lprevious',
\ 'lprev': 'lprevious',
\ 'lprevi': 'lprevious',
\ 'lprevio': 'lprevious',
\ 'lpreviou': 'lprevious',
\ 'lr': 'lrewind',
\ 'lre': 'lrewind',
\ 'lrew': 'lrewind',
\ 'lrewi': 'lrewind',
\ 'lrewin': 'lrewind',
\ 'lt': 'ltag',
\ 'lta': 'ltag',
\ 'lu': 'lunmap',
\ 'luad': 'luado',
\ 'luaf': 'luafile',
\ 'luafi': 'luafile',
\ 'luafil': 'luafile',
\ 'lun': 'lunmap',
\ 'lunm': 'lunmap',
\ 'lunma': 'lunmap',
\ 'lv': 'lvimgrep',
\ 'lvi': 'lvimgrep',
\ 'lvim': 'lvimgrep',
\ 'lvimg': 'lvimgrep',
\ 'lvimgr': 'lvimgrep',
\ 'lvimgre': 'lvimgrep',
\ 'lvimgrepa': 'lvimgrepadd',
\ 'lvimgrepad': 'lvimgrepadd',
\ 'lw': 'lwindow',
\ 'lwi': 'lwindow',
\ 'lwin': 'lwindow',
\ 'lwind': 'lwindow',
\ 'lwindo': 'lwindow',
\ 'm': 'move',
\ 'ma': 'mark',
\ 'mak': 'make',
\ 'mapc': 'mapclear',
\ 'mapcl': 'mapclear',
\ 'mapcle': 'mapclear',
\ 'mapclea': 'mapclear',
\ 'mar': 'mark',
\ 'mat': 'match',
\ 'matc': 'match',
\ 'me': 'menu',
\ 'men': 'menu',
\ 'menut': 'menutranslate',
\ 'menutr': 'menutranslate',
\ 'menutra': 'menutranslate',
\ 'menutran': 'menutranslate',
\ 'menutrans': 'menutranslate',
\ 'menutransl': 'menutranslate',
\ 'menutransla': 'menutranslate',
\ 'menutranslat': 'menutranslate',
\ 'mes': 'messages',
\ 'mess': 'messages',
\ 'messa': 'messages',
\ 'messag': 'messages',
\ 'message': 'messages',
\ 'mk': 'mkexrc',
\ 'mke': 'mkexrc',
\ 'mkex': 'mkexrc',
\ 'mkexr': 'mkexrc',
\ 'mks': 'mksession',
\ 'mkse': 'mksession',
\ 'mkses': 'mksession',
\ 'mksess': 'mksession',
\ 'mksessi': 'mksession',
\ 'mksessio': 'mksession',
\ 'mksp': 'mkspell',
\ 'mkspe': 'mkspell',
\ 'mkspel': 'mkspell',
\ 'mkv': 'mkvimrc',
\ 'mkvi': 'mkvimrc',
\ 'mkvie': 'mkview',
\ 'mkvim': 'mkvimrc',
\ 'mkvimr': 'mkvimrc',
\ 'mo': 'move',
\ 'mod': 'mode',
\ 'mov': 'move',
\ 'mz': 'mzscheme',
\ 'mzf': 'mzfile',
\ 'mzfi': 'mzfile',
\ 'mzfil': 'mzfile',
\ 'mzs': 'mzscheme',
\ 'mzsc': 'mzscheme',
\ 'mzsch': 'mzscheme',
\ 'mzsche': 'mzscheme',
\ 'mzschem': 'mzscheme',
\ 'n': 'next',
\ 'nb': 'nbkey',
\ 'nbc': 'nbclose',
\ 'nbcl': 'nbclose',
\ 'nbclo': 'nbclose',
\ 'nbclos': 'nbclose',
\ 'nbk': 'nbkey',
\ 'nbke': 'nbkey',
\ 'nbs': 'nbstart',
\ 'nbsa': 'nbstart',
\ 'nbsar': 'nbstart',
\ 'nbsart': 'nbstart',
\ 'ne': 'next',
\ 'nex': 'next',
\ 'nm': 'nmap',
\ 'nma': 'nmap',
\ 'nmapc': 'nmapclear',
\ 'nmapcl': 'nmapclear',
\ 'nmapcle': 'nmapclear',
\ 'nmapclea': 'nmapclear',
\ 'nme': 'nmenu',
\ 'nmen': 'nmenu',
\ 'nn': 'nnoremap',
\ 'nno': 'nnoremap',
\ 'nnor': 'nnoremap',
\ 'nnore': 'nnoremap',
\ 'nnorem': 'nnoremap',
\ 'nnorema': 'nnoremap',
\ 'nnoreme': 'nnoremenu',
\ 'nnoremen': 'nnoremenu',
\ 'no': 'noremap',
\ 'noa': 'noautocmd',
\ 'noau': 'noautocmd',
\ 'noaut': 'noautocmd',
\ 'noauto': 'noautocmd',
\ 'noautoc': 'noautocmd',
\ 'noautocm': 'noautocmd',
\ 'noh': 'nohlsearch',
\ 'nohl': 'nohlsearch',
\ 'nohls': 'nohlsearch',
\ 'nohlse': 'nohlsearch',
\ 'nohlsea': 'nohlsearch',
\ 'nohlsear': 'nohlsearch',
\ 'nohlsearc': 'nohlsearch',
\ 'nor': 'noremap',
\ 'nore': 'noremap',
\ 'norea': 'noreabbrev',
\ 'noreab': 'noreabbrev',
\ 'noreabb': 'noreabbrev',
\ 'noreabbr': 'noreabbrev',
\ 'noreabbre': 'noreabbrev',
\ 'norem': 'noremap',
\ 'norema': 'noremap',
\ 'noreme': 'noremenu',
\ 'noremen': 'noremenu',
\ 'norm': 'normal',
\ 'norma': 'normal',
\ 'nos': 'noswapfile',
\ 'nosw': 'noswapfile',
\ 'noswa': 'noswapfile',
\ 'noswap': 'noswapfile',
\ 'noswapf': 'noswapfile',
\ 'noswapfi': 'noswapfile',
\ 'noswapfil': 'noswapfile',
\ 'nu': 'number',
\ 'num': 'number',
\ 'numb': 'number',
\ 'numbe': 'number',
\ 'nun': 'nunmap',
\ 'nunm': 'nunmap',
\ 'nunma': 'nunmap',
\ 'nunme': 'nunmenu',
\ 'nunmen': 'nunmenu',
\ 'o': 'open',
\ 'ol': 'oldfiles',
\ 'old': 'oldfiles',
\ 'oldf': 'oldfiles',
\ 'oldfi': 'oldfiles',
\ 'oldfil': 'oldfiles',
\ 'oldfile': 'oldfiles',
\ 'om': 'omap',
\ 'oma': 'omap',
\ 'omapc': 'omapclear',
\ 'omapcl': 'omapclear',
\ 'omapcle': 'omapclear',
\ 'omapclea': 'omapclear',
\ 'ome': 'omenu',
\ 'omen': 'omenu',
\ 'on': 'only',
\ 'onl': 'only',
\ 'ono': 'onoremap',
\ 'onor': 'onoremap',
\ 'onore': 'onoremap',
\ 'onorem': 'onoremap',
\ 'onorema': 'onoremap',
\ 'onoreme': 'onoremenu',
\ 'onoremen': 'onoremenu',
\ 'op': 'open',
\ 'ope': 'open',
\ 'opt': 'options',
\ 'opti': 'options',
\ 'optio': 'options',
\ 'option': 'options',
\ 'ou': 'ounmap',
\ 'oun': 'ounmap',
\ 'ounm': 'ounmap',
\ 'ounma': 'ounmap',
\ 'ounme': 'ounmenu',
\ 'ounmen': 'ounmenu',
\ 'ow': 'ownsyntax',
\ 'own': 'ownsyntax',
\ 'owns': 'ownsyntax',
\ 'ownsy': 'ownsyntax',
\ 'ownsyn': 'ownsyntax',
\ 'ownsynt': 'ownsyntax',
\ 'ownsynta': 'ownsyntax',
\ 'p': 'print',
\ 'pc': 'pclose',
\ 'pcl': 'pclose',
\ 'pclo': 'pclose',
\ 'pclos': 'pclose',
\ 'pe': 'perl',
\ 'ped': 'pedit',
\ 'pedi': 'pedit',
\ 'per': 'perl',
\ 'perld': 'perldo',
\ 'po': 'pop',
\ 'pp': 'ppop',
\ 'ppo': 'ppop',
\ 'pr': 'print',
\ 'pre': 'preserve',
\ 'pres': 'preserve',
\ 'prese': 'preserve',
\ 'preser': 'preserve',
\ 'preserv': 'preserve',
\ 'prev': 'previous',
\ 'previ': 'previous',
\ 'previo': 'previous',
\ 'previou': 'previous',
\ 'pri': 'print',
\ 'prin': 'print',
\ 'pro': 'promptfind',
\ 'prof': 'profile',
\ 'profd': 'profdel',
\ 'profde': 'profdel',
\ 'profi': 'profile',
\ 'profil': 'profile',
\ 'prom': 'promptfind',
\ 'promp': 'promptfind',
\ 'prompt': 'promptfind',
\ 'promptf': 'promptfind',
\ 'promptfi': 'promptfind',
\ 'promptfin': 'promptfind',
\ 'promptr': 'promptrepl',
\ 'promptre': 'promptrepl',
\ 'promptrep': 'promptrepl',
\ 'ps': 'psearch',
\ 'pse': 'psearch',
\ 'psea': 'psearch',
\ 'psear': 'psearch',
\ 'psearc': 'psearch',
\ 'pt': 'ptag',
\ 'ptN': 'ptNext',
\ 'ptNe': 'ptNext',
\ 'ptNex': 'ptNext',
\ 'pta': 'ptag',
\ 'ptf': 'ptfirst',
\ 'ptfi': 'ptfirst',
\ 'ptfir': 'ptfirst',
\ 'ptfirs': 'ptfirst',
\ 'ptj': 'ptjump',
\ 'ptju': 'ptjump',
\ 'ptjum': 'ptjump',
\ 'ptl': 'ptlast',
\ 'ptla': 'ptlast',
\ 'ptlas': 'ptlast',
\ 'ptn': 'ptnext',
\ 'ptne': 'ptnext',
\ 'ptnex': 'ptnext',
\ 'ptp': 'ptprevious',
\ 'ptpr': 'ptprevious',
\ 'ptpre': 'ptprevious',
\ 'ptprev': 'ptprevious',
\ 'ptprevi': 'ptprevious',
\ 'ptprevio': 'ptprevious',
\ 'ptpreviou': 'ptprevious',
\ 'ptr': 'ptrewind',
\ 'ptre': 'ptrewind',
\ 'ptrew': 'ptrewind',
\ 'ptrewi': 'ptrewind',
\ 'ptrewin': 'ptrewind',
\ 'pts': 'ptselect',
\ 'ptse': 'ptselect',
\ 'ptsel': 'ptselect',
\ 'ptsele': 'ptselect',
\ 'ptselec': 'ptselect',
\ 'pu': 'put',
\ 'pw': 'pwd',
\ 'py': 'python',
\ 'pyd': 'pydo',
\ 'pyf': 'pyfile',
\ 'pyfi': 'pyfile',
\ 'pyfil': 'pyfile',
\ 'pyt': 'python',
\ 'pyth': 'python',
\ 'pytho': 'python',
\ 'q': 'quit',
\ 'qa': 'qall',
\ 'qal': 'qall',
\ 'qu': 'quit',
\ 'qui': 'quit',
\ 'quita': 'quitall',
\ 'quital': 'quitall',
\ 'r': 'read',
\ 're': 'read',
\ 'rea': 'read',
\ 'rec': 'recover',
\ 'reco': 'recover',
\ 'recov': 'recover',
\ 'recove': 'recover',
\ 'red': 'redo',
\ 'redi': 'redir',
\ 'redr': 'redraw',
\ 'redra': 'redraw',
\ 'redraws': 'redrawstatus',
\ 'redrawst': 'redrawstatus',
\ 'redrawsta': 'redrawstatus',
\ 'redrawstat': 'redrawstatus',
\ 'redrawstatu': 'redrawstatus',
\ 'reg': 'registers',
\ 'regi': 'registers',
\ 'regis': 'registers',
\ 'regist': 'registers',
\ 'registe': 'registers',
\ 'register': 'registers',
\ 'res': 'resize',
\ 'resi': 'resize',
\ 'resiz': 'resize',
\ 'ret': 'retab',
\ 'reta': 'retab',
\ 'retu': 'return',
\ 'retur': 'return',
\ 'rew': 'rewind',
\ 'rewi': 'rewind',
\ 'rewin': 'rewind',
\ 'ri': 'right',
\ 'rig': 'right',
\ 'righ': 'right',
\ 'rightb': 'rightbelow',
\ 'rightbe': 'rightbelow',
\ 'rightbel': 'rightbelow',
\ 'rightbelo': 'rightbelow',
\ 'ru': 'runtime',
\ 'rub': 'ruby',
\ 'rubyd': 'rubydo',
\ 'rubyf': 'rubyfile',
\ 'rubyfi': 'rubyfile',
\ 'rubyfil': 'rubyfile',
\ 'run': 'runtime',
\ 'rund': 'rundo',
\ 'runt': 'runtime',
\ 'runti': 'runtime',
\ 'runtim': 'runtime',
\ 'rv': 'rviminfo',
\ 'rvi': 'rviminfo',
\ 'rvim': 'rviminfo',
\ 'rvimi': 'rviminfo',
\ 'rvimin': 'rviminfo',
\ 'rviminf': 'rviminfo',
\ 's': 'substitute',
\ 'sN': 'sNext',
\ 'sNe': 'sNext',
\ 'sNex': 'sNext',
\ 'sa': 'sargument',
\ 'sal': 'sall',
\ 'san': 'sandbox',
\ 'sand': 'sandbox',
\ 'sandb': 'sandbox',
\ 'sandbo': 'sandbox',
\ 'sar': 'sargument',
\ 'sarg': 'sargument',
\ 'sargu': 'sargument',
\ 'sargum': 'sargument',
\ 'sargume': 'sargument',
\ 'sargumen': 'sargument',
\ 'sav': 'saveas',
\ 'save': 'saveas',
\ 'savea': 'saveas',
\ 'sb': 'sbuffer',
\ 'sbN': 'sbNext',
\ 'sbNe': 'sbNext',
\ 'sbNex': 'sbNext',
\ 'sba': 'sball',
\ 'sbal': 'sball',
\ 'sbf': 'sbfirst',
\ 'sbfi': 'sbfirst',
\ 'sbfir': 'sbfirst',
\ 'sbfirs': 'sbfirst',
\ 'sbl': 'sblast',
\ 'sbla': 'sblast',
\ 'sblas': 'sblast',
\ 'sbm': 'sbmodified',
\ 'sbmo': 'sbmodified',
\ 'sbmod': 'sbmodified',
\ 'sbmodi': 'sbmodified',
\ 'sbmodif': 'sbmodified',
\ 'sbmodifi': 'sbmodified',
\ 'sbmodifie': 'sbmodified',
\ 'sbn': 'sbnext',
\ 'sbne': 'sbnext',
\ 'sbnex': 'sbnext',
\ 'sbp': 'sbprevious',
\ 'sbpr': 'sbprevious',
\ 'sbpre': 'sbprevious',
\ 'sbprev': 'sbprevious',
\ 'sbprevi': 'sbprevious',
\ 'sbprevio': 'sbprevious',
\ 'sbpreviou': 'sbprevious',
\ 'sbr': 'sbrewind',
\ 'sbre': 'sbrewind',
\ 'sbrew': 'sbrewind',
\ 'sbrewi': 'sbrewind',
\ 'sbrewin': 'sbrewind',
\ 'sbu': 'sbuffer',
\ 'sbuf': 'sbuffer',
\ 'sbuff': 'sbuffer',
\ 'sbuffe': 'sbuffer',
\ 'scrip': 'scriptnames',
\ 'script': 'scriptnames',
\ 'scripte': 'scriptencoding',
\ 'scripten': 'scriptencoding',
\ 'scriptenc': 'scriptencoding',
\ 'scriptenco': 'scriptencoding',
\ 'scriptencod': 'scriptencoding',
\ 'scriptencodi': 'scriptencoding',
\ 'scriptencodin': 'scriptencoding',
\ 'scriptn': 'scriptnames',
\ 'scriptna': 'scriptnames',
\ 'scriptnam': 'scriptnames',
\ 'scriptname': 'scriptnames',
\ 'scs': 'scscope',
\ 'scsc': 'scscope',
\ 'scsco': 'scscope',
\ 'scscop': 'scscope',
\ 'se': 'set',
\ 'setf': 'setfiletype',
\ 'setfi': 'setfiletype',
\ 'setfil': 'setfiletype',
\ 'setfile': 'setfiletype',
\ 'setfilet': 'setfiletype',
\ 'setfilety': 'setfiletype',
\ 'setfiletyp': 'setfiletype',
\ 'setg': 'setglobal',
\ 'setgl': 'setglobal',
\ 'setglo': 'setglobal',
\ 'setglob': 'setglobal',
\ 'setgloba': 'setglobal',
\ 'setl': 'setlocal',
\ 'setlo': 'setlocal',
\ 'setloc': 'setlocal',
\ 'setloca': 'setlocal',
\ 'sf': 'sfind',
\ 'sfi': 'sfind',
\ 'sfin': 'sfind',
\ 'sfir': 'sfirst',
\ 'sfirs': 'sfirst',
\ 'sh': 'shell',
\ 'she': 'shell',
\ 'shel': 'shell',
\ 'si': 'simalt',
\ 'sig': 'sign',
\ 'sil': 'silent',
\ 'sile': 'silent',
\ 'silen': 'silent',
\ 'sim': 'simalt',
\ 'sima': 'simalt',
\ 'simal': 'simalt',
\ 'sl': 'sleep',
\ 'sla': 'slast',
\ 'slas': 'slast',
\ 'sle': 'sleep',
\ 'slee': 'sleep',
\ 'sm': 'smagic',
\ 'sma': 'smagic',
\ 'smag': 'smagic',
\ 'smagi': 'smagic',
\ 'smapc': 'smapclear',
\ 'smapcl': 'smapclear',
\ 'smapcle': 'smapclear',
\ 'smapclea': 'smapclear',
\ 'sme': 'smenu',
\ 'smen': 'smenu',
\ 'sn': 'snext',
\ 'sne': 'snext',
\ 'snex': 'snext',
\ 'sni': 'sniff',
\ 'snif': 'sniff',
\ 'sno': 'snomagic',
\ 'snom': 'snomagic',
\ 'snoma': 'snomagic',
\ 'snomag': 'snomagic',
\ 'snomagi': 'snomagic',
\ 'snor': 'snoremap',
\ 'snore': 'snoremap',
\ 'snorem': 'snoremap',
\ 'snorema': 'snoremap',
\ 'snoreme': 'snoremenu',
\ 'snoremen': 'snoremenu',
\ 'so': 'source',
\ 'sor': 'sort',
\ 'sou': 'source',
\ 'sour': 'source',
\ 'sourc': 'source',
\ 'sp': 'split',
\ 'spe': 'spellgood',
\ 'spel': 'spellgood',
\ 'spell': 'spellgood',
\ 'spelld': 'spelldump',
\ 'spelldu': 'spelldump',
\ 'spelldum': 'spelldump',
\ 'spellg': 'spellgood',
\ 'spellgo': 'spellgood',
\ 'spellgoo': 'spellgood',
\ 'spelli': 'spellinfo',
\ 'spellin': 'spellinfo',
\ 'spellinf': 'spellinfo',
\ 'spellr': 'spellrepall',
\ 'spellre': 'spellrepall',
\ 'spellrep': 'spellrepall',
\ 'spellrepa': 'spellrepall',
\ 'spellrepal': 'spellrepall',
\ 'spellu': 'spellundo',
\ 'spellun': 'spellundo',
\ 'spellund': 'spellundo',
\ 'spellw': 'spellwrong',
\ 'spellwr': 'spellwrong',
\ 'spellwro': 'spellwrong',
\ 'spellwron': 'spellwrong',
\ 'spl': 'split',
\ 'spli': 'split',
\ 'spr': 'sprevious',
\ 'spre': 'sprevious',
\ 'sprev': 'sprevious',
\ 'sprevi': 'sprevious',
\ 'sprevio': 'sprevious',
\ 'spreviou': 'sprevious',
\ 'sre': 'srewind',
\ 'srew': 'srewind',
\ 'srewi': 'srewind',
\ 'srewin': 'srewind',
\ 'st': 'stop',
\ 'sta': 'stag',
\ 'star': 'startinsert',
\ 'start': 'startinsert',
\ 'startg': 'startgreplace',
\ 'startgr': 'startgreplace',
\ 'startgre': 'startgreplace',
\ 'startgrep': 'startgreplace',
\ 'startgrepl': 'startgreplace',
\ 'startgrepla': 'startgreplace',
\ 'startgreplac': 'startgreplace',
\ 'starti': 'startinsert',
\ 'startin': 'startinsert',
\ 'startins': 'startinsert',
\ 'startinse': 'startinsert',
\ 'startinser': 'startinsert',
\ 'startr': 'startreplace',
\ 'startre': 'startreplace',
\ 'startrep': 'startreplace',
\ 'startrepl': 'startreplace',
\ 'startrepla': 'startreplace',
\ 'startreplac': 'startreplace',
\ 'stj': 'stjump',
\ 'stju': 'stjump',
\ 'stjum': 'stjump',
\ 'sto': 'stop',
\ 'stopi': 'stopinsert',
\ 'stopin': 'stopinsert',
\ 'stopins': 'stopinsert',
\ 'stopinse': 'stopinsert',
\ 'stopinser': 'stopinsert',
\ 'sts': 'stselect',
\ 'stse': 'stselect',
\ 'stsel': 'stselect',
\ 'stsele': 'stselect',
\ 'stselec': 'stselect',
\ 'su': 'substitute',
\ 'sub': 'substitute',
\ 'subs': 'substitute',
\ 'subst': 'substitute',
\ 'substi': 'substitute',
\ 'substit': 'substitute',
\ 'substitu': 'substitute',
\ 'substitut': 'substitute',
\ 'sun': 'sunhide',
\ 'sunh': 'sunhide',
\ 'sunhi': 'sunhide',
\ 'sunhid': 'sunhide',
\ 'sunm': 'sunmap',
\ 'sunma': 'sunmap',
\ 'sunme': 'sunmenu',
\ 'sunmen': 'sunmenu',
\ 'sus': 'suspend',
\ 'susp': 'suspend',
\ 'suspe': 'suspend',
\ 'suspen': 'suspend',
\ 'sv': 'sview',
\ 'svi': 'sview',
\ 'svie': 'sview',
\ 'sw': 'swapname',
\ 'swa': 'swapname',
\ 'swap': 'swapname',
\ 'swapn': 'swapname',
\ 'swapna': 'swapname',
\ 'swapnam': 'swapname',
\ 'sy': 'syntax',
\ 'syn': 'syntax',
\ 'sync': 'syncbind',
\ 'syncb': 'syncbind',
\ 'syncbi': 'syncbind',
\ 'syncbin': 'syncbind',
\ 'synt': 'syntax',
\ 'synta': 'syntax',
\ 'synti': 'syntime',
\ 'syntim': 'syntime',
\ 'tN': 'tNext',
\ 'tNe': 'tNext',
\ 'tNex': 'tNext',
\ 'ta': 'tag',
\ 'tabN': 'tabNext',
\ 'tabNe': 'tabNext',
\ 'tabNex': 'tabNext',
\ 'tabc': 'tabclose',
\ 'tabcl': 'tabclose',
\ 'tabclo': 'tabclose',
\ 'tabclos': 'tabclose',
\ 'tabe': 'tabedit',
\ 'tabed': 'tabedit',
\ 'tabedi': 'tabedit',
\ 'tabf': 'tabfind',
\ 'tabfi': 'tabfind',
\ 'tabfin': 'tabfind',
\ 'tabfir': 'tabfirst',
\ 'tabfirs': 'tabfirst',
\ 'tabl': 'tablast',
\ 'tabla': 'tablast',
\ 'tablas': 'tablast',
\ 'tabm': 'tabmove',
\ 'tabmo': 'tabmove',
\ 'tabmov': 'tabmove',
\ 'tabn': 'tabnext',
\ 'tabne': 'tabnext',
\ 'tabnex': 'tabnext',
\ 'tabo': 'tabonly',
\ 'tabon': 'tabonly',
\ 'tabonl': 'tabonly',
\ 'tabp': 'tabprevious',
\ 'tabpr': 'tabprevious',
\ 'tabpre': 'tabprevious',
\ 'tabprev': 'tabprevious',
\ 'tabprevi': 'tabprevious',
\ 'tabprevio': 'tabprevious',
\ 'tabpreviou': 'tabprevious',
\ 'tabr': 'tabrewind',
\ 'tabre': 'tabrewind',
\ 'tabrew': 'tabrewind',
\ 'tabrewi': 'tabrewind',
\ 'tabrewin': 'tabrewind',
\ 'tc': 'tcl',
\ 'tcld': 'tcldo',
\ 'tclf': 'tclfile',
\ 'tclfi': 'tclfile',
\ 'tclfil': 'tclfile',
\ 'te': 'tearoff',
\ 'tea': 'tearoff',
\ 'tear': 'tearoff',
\ 'tearo': 'tearoff',
\ 'tearof': 'tearoff',
\ 'tf': 'tfirst',
\ 'tfi': 'tfirst',
\ 'tfir': 'tfirst',
\ 'tfirs': 'tfirst',
\ 'th': 'throw',
\ 'thr': 'throw',
\ 'thro': 'throw',
\ 'tj': 'tjump',
\ 'tju': 'tjump',
\ 'tjum': 'tjump',
\ 'tl': 'tlast',
\ 'tla': 'tlast',
\ 'tlas': 'tlast',
\ 'tm': 'tmenu',
\ 'tme': 'tmenu',
\ 'tmen': 'tmenu',
\ 'tn': 'tnext',
\ 'tne': 'tnext',
\ 'tnex': 'tnext',
\ 'to': 'topleft',
\ 'top': 'topleft',
\ 'topl': 'topleft',
\ 'tople': 'topleft',
\ 'toplef': 'topleft',
\ 'tp': 'tprevious',
\ 'tpr': 'tprevious',
\ 'tpre': 'tprevious',
\ 'tprev': 'tprevious',
\ 'tprevi': 'tprevious',
\ 'tprevio': 'tprevious',
\ 'tpreviou': 'tprevious',
\ 'tr': 'trewind',
\ 'tre': 'trewind',
\ 'trew': 'trewind',
\ 'trewi': 'trewind',
\ 'trewin': 'trewind',
\ 'ts': 'tselect',
\ 'tse': 'tselect',
\ 'tsel': 'tselect',
\ 'tsele': 'tselect',
\ 'tselec': 'tselect',
\ 'tu': 'tunmenu',
\ 'tun': 'tunmenu',
\ 'tunm': 'tunmenu',
\ 'tunme': 'tunmenu',
\ 'tunmen': 'tunmenu',
\ 'u': 'undo',
\ 'un': 'undo',
\ 'und': 'undo',
\ 'undoj': 'undojoin',
\ 'undojo': 'undojoin',
\ 'undojoi': 'undojoin',
\ 'undol': 'undolist',
\ 'undoli': 'undolist',
\ 'undolis': 'undolist',
\ 'unh': 'unhide',
\ 'unhi': 'unhide',
\ 'unhid': 'unhide',
\ 'unl': 'unlet',
\ 'unle': 'unlet',
\ 'unlo': 'unlockvar',
\ 'unloc': 'unlockvar',
\ 'unlock': 'unlockvar',
\ 'unlockv': 'unlockvar',
\ 'unlockva': 'unlockvar',
\ 'unm': 'unmap',
\ 'unma': 'unmap',
\ 'unme': 'unmenu',
\ 'unmen': 'unmenu',
\ 'uns': 'unsilent',
\ 'unsi': 'unsilent',
\ 'unsil': 'unsilent',
\ 'unsile': 'unsilent',
\ 'unsilen': 'unsilent',
\ 'up': 'update',
\ 'upd': 'update',
\ 'upda': 'update',
\ 'updat': 'update',
\ 'v': 'vglobal',
\ 've': 'version',
\ 'ver': 'version',
\ 'verb': 'verbose',
\ 'verbo': 'verbose',
\ 'verbos': 'verbose',
\ 'vers': 'version',
\ 'versi': 'version',
\ 'versio': 'version',
\ 'vert': 'vertical',
\ 'verti': 'vertical',
\ 'vertic': 'vertical',
\ 'vertica': 'vertical',
\ 'vg': 'vglobal',
\ 'vgl': 'vglobal',
\ 'vglo': 'vglobal',
\ 'vglob': 'vglobal',
\ 'vgloba': 'vglobal',
\ 'vi': 'visual',
\ 'vie': 'view',
\ 'vim': 'vimgrep',
\ 'vimg': 'vimgrep',
\ 'vimgr': 'vimgrep',
\ 'vimgre': 'vimgrep',
\ 'vimgrepa': 'vimgrepadd',
\ 'vimgrepad': 'vimgrepadd',
\ 'vis': 'visual',
\ 'visu': 'visual',
\ 'visua': 'visual',
\ 'viu': 'viusage',
\ 'vius': 'viusage',
\ 'viusa': 'viusage',
\ 'viusag': 'viusage',
\ 'vm': 'vmap',
\ 'vma': 'vmap',
\ 'vmapc': 'vmapclear',
\ 'vmapcl': 'vmapclear',
\ 'vmapcle': 'vmapclear',
\ 'vmapclea': 'vmapclear',
\ 'vme': 'vmenu',
\ 'vmen': 'vmenu',
\ 'vn': 'vnoremap',
\ 'vne': 'vnew',
\ 'vno': 'vnoremap',
\ 'vnor': 'vnoremap',
\ 'vnore': 'vnoremap',
\ 'vnorem': 'vnoremap',
\ 'vnorema': 'vnoremap',
\ 'vnoreme': 'vnoremenu',
\ 'vnoremen': 'vnoremenu',
\ 'vs': 'vsplit',
\ 'vsp': 'vsplit',
\ 'vspl': 'vsplit',
\ 'vspli': 'vsplit',
\ 'vu': 'vunmap',
\ 'vun': 'vunmap',
\ 'vunm': 'vunmap',
\ 'vunma': 'vunmap',
\ 'vunme': 'vunmenu',
\ 'vunmen': 'vunmenu',
\ 'w': 'write',
\ 'wN': 'wNext',
\ 'wNe': 'wNext',
\ 'wNex': 'wNext',
\ 'wa': 'wall',
\ 'wal': 'wall',
\ 'wh': 'while',
\ 'whi': 'while',
\ 'whil': 'while',
\ 'wi': 'winsize',
\ 'win': 'winsize',
\ 'winc': 'wincmd',
\ 'wincm': 'wincmd',
\ 'winp': 'winpos',
\ 'winpo': 'winpos',
\ 'wins': 'winsize',
\ 'winsi': 'winsize',
\ 'winsiz': 'winsize',
\ 'wn': 'wnext',
\ 'wne': 'wnext',
\ 'wnex': 'wnext',
\ 'wp': 'wprevious',
\ 'wpr': 'wprevious',
\ 'wpre': 'wprevious',
\ 'wprev': 'wprevious',
\ 'wprevi': 'wprevious',
\ 'wprevio': 'wprevious',
\ 'wpreviou': 'wprevious',
\ 'wqa': 'wqall',
\ 'wqal': 'wqall',
\ 'wr': 'write',
\ 'wri': 'write',
\ 'writ': 'write',
\ 'ws': 'wsverb',
\ 'wsv': 'wsverb',
\ 'wsve': 'wsverb',
\ 'wsver': 'wsverb',
\ 'wu': 'wundo',
\ 'wun': 'wundo',
\ 'wund': 'wundo',
\ 'wv': 'wviminfo',
\ 'wvi': 'wviminfo',
\ 'wvim': 'wviminfo',
\ 'wvimi': 'wviminfo',
\ 'wvimin': 'wviminfo',
\ 'wviminf': 'wviminfo',
\ 'x': 'xit',
\ 'xa': 'xall',
\ 'xal': 'xall',
\ 'xi': 'xit',
\ 'xm': 'xmap',
\ 'xma': 'xmap',
\ 'xmapc': 'xmapclear',
\ 'xmapcl': 'xmapclear',
\ 'xmapcle': 'xmapclear',
\ 'xmapclea': 'xmapclear',
\ 'xme': 'xmenu',
\ 'xmen': 'xmenu',
\ 'xn': 'xnoremap',
\ 'xno': 'xnoremap',
\ 'xnor': 'xnoremap',
\ 'xnore': 'xnoremap',
\ 'xnorem': 'xnoremap',
\ 'xnorema': 'xnoremap',
\ 'xnoreme': 'xnoremenu',
\ 'xnoremen': 'xnoremenu',
\ 'xu': 'xunmap',
\ 'xun': 'xunmap',
\ 'xunm': 'xunmap',
\ 'xunma': 'xunmap',
\ 'xunme': 'xunmenu',
\ 'xunmen': 'xunmenu',
\ 'y': 'yank',
\ 'ya': 'yank',
\ 'yan': 'yank',
\ }

let &cpo = s:save_cpo
unlet s:save_cpo
